# This is a basic workflow to help you get started with Actions
name: Docker Builds

# Trigger on release
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
permissions: 
  contents: read
  packages: write
jobs:
  build_deploy_to_registry:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Enable docker cache to speed-up builds
      - name: Setup Docker build cache
        uses: actions/cache@v2
        with:
          path: /tmp/buildx-cache
          key: ${{runner.os}}-buildx-${{github.sha}}
          restore-keys: |
            ${{runner.os}}-buildx-
      # Enable multi-architecture support on build node
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - run: docker context create mycontext
      - run: docker context use mycontext
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
         buildkitd-flags: --debug
         endpoint: mycontext

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: get tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["user/image:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
      - name: Build + Push image (tag = git release tag)
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/buildx-cache \
            --cache-to type=local,dest=/tmp/buildx-cache \
            --label org.opencontainers.image.revision="${{github.sha}}" \
            --platform "linux/arm/v7,linux/arm64,linux/amd64" \
            --pull \
            --tag "${{secrets.REGISTRY_NAME}}/exporters/mac_ups_exporter:${GITHUB_REF#refs/tags/}" \
            --output "type=image,push=true" \
            --file ./Dockerfile .
      - name: Build + Push image ("latest")
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/buildx-cache \
            --cache-to type=local,dest=/tmp/buildx-cache \
            --label org.opencontainers.image.revision="${{github.sha}}" \
            --platform "linux/arm/v7,linux/arm64,linux/amd64" \
            --tag "${{secrets.REGISTRY_NAME}}/devops/mac_ups_exporter:${{ fromJson(steps.gen_tags.outputs.tags) }}" \
            --output "type=image,push=true" \
            --file ./Dockerfile .